# Generated by Django 3.2.16 on 2024-02-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_measurument_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='measurument_unit',
        ),
    ]
