# Generated by Django 3.2.16 on 2023-01-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230121_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='reciepe',
            new_name='recipe',
        ),
    ]
