# Generated by Django 3.2.16 on 2023-01-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже существует'}, max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Введите уникальное имя пользователя. Максимум 150 символов. Используйте только английские буквы, цифры и символы @/./+/-/_', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
