# Generated by Django 3.2.16 on 2023-01-25 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230125_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
