# Generated by Django 3.2.16 on 2023-01-26 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
